// Package web embeds the production frontend build so the server binary can
// serve it. dist/ is generated by `bun run build`; in checkouts without a
// build, only dist/.gitkeep is embedded and the server stays API-only.
package web

import (
	"embed"
	"io/fs"
)

//go:embed all:dist
var dist embed.FS

// Dist returns the frontend build rooted at its own top level, so index.html
// sits at the root of the returned filesystem.
func Dist() fs.FS {
	sub, err := fs.Sub(dist, "dist")
	if err != nil {
		// The embed directive guarantees dist exists at compile time.
		panic(err)
	}
	return sub
}
